import type { CatalogLocale } from '../types'

export const locale: CatalogLocale = {
  skills: [
    {
      id: 'longbridge',
      pkg: 'longbridge',
      cat: 'meta',
      tools: 10,
      tagType: 'hot',
      name: 'Longbridge Overview',
      desc: 'Full-stack financial data and trading platform — CLI, Python/Rust SDK, MCP, and LLM integration. The catch-all entry point for any market or account query.',
      prompt: 'What is NVDA\'s current price, recent news, and how does it affect my positions?',
    },
    {
      id: 'market-data',
      pkg: 'longbridge-market-data',
      cat: 'quote',
      tools: 8,
      tagType: 'hot',
      name: 'Market Data',
      desc: 'Real-time quotes, K-lines, order book, capital flow, market temperature, FX rates, IPO calendar, and ADR premium for HK/US/A-share/SG.',
      prompt: 'Get NVDA\'s current price, 6-month daily chart, and today\'s capital flow.',
    },
    {
      id: 'content',
      pkg: 'longbridge-content',
      cat: 'discovery',
      tools: 4,
      name: 'News & Filings',
      desc: 'Stock news, regulatory filings (SEC 10-K/10-Q/8-K), community discussion topics, and market rule reference.',
      prompt: 'Summarize META\'s AI-related news from the past week.',
    },
    {
      id: 'intel',
      pkg: 'longbridge-intel',
      cat: 'discovery',
      tools: 8,
      tagType: 'hot',
      name: 'Market Intelligence',
      desc: 'Strategy screener, popularity rankings, top movers, anomalies, ETF flows, sector rotation, supply chain, morning briefings, and ARK-style innovation analysis.',
      prompt: 'Screen US tech stocks with MACD golden cross and market cap above $50B.',
    },
    {
      id: 'watchlist',
      pkg: 'longbridge-watchlist',
      cat: 'discovery',
      tools: 5,
      name: 'Watchlist & Alerts',
      desc: 'Watchlist group management, price alerts, and community stock lists — all writes require two-step confirmation.',
      prompt: 'Add NVDA and TSLA to my "AI Compute" watchlist and alert me when NVDA hits 200.',
    },
    {
      id: 'derivatives',
      pkg: 'longbridge-derivatives',
      cat: 'derivative',
      tools: 5,
      tagType: 'hot',
      name: 'Options & Warrants',
      desc: 'US/HK option chain with IV and Greeks, open interest by strike; HK warrants and CBBCs with issuer listings.',
      prompt: 'List TSLA call options expiring next week near the money with IV and delta.',
    },
    {
      id: 'research',
      pkg: 'longbridge-research',
      cat: 'research',
      tools: 6,
      name: 'Research',
      desc: 'Institution ratings, consensus price targets, EPS forecasts, shareholder data, fund holders, insider trades (Form 4), short interest, and industry rankings.',
      prompt: 'Who are NVDA\'s top institutional holders and how did they move last quarter?',
    },
    {
      id: 'fundamentals',
      pkg: 'longbridge-fundamentals',
      cat: 'research',
      tools: 8,
      name: 'Fundamentals',
      desc: 'Financial statements, valuation multiples (PE/PB/PS), business segments, dividends, operating data, corporate actions, company profiles, and DCF frameworks.',
      prompt: 'Give me NVDA\'s latest quarterly revenue, gross margin, EPS, and PE percentile.',
    },
    {
      id: 'earnings',
      pkg: 'longbridge-earnings',
      cat: 'research',
      tools: 3,
      tagType: 'hot',
      name: 'Earnings',
      desc: 'Pre-earnings preview (guidance review, events, Q&A, key things to watch) and post-earnings analysis (beat/miss, segments, guidance, estimates, valuation).',
      prompt: 'Do a post-earnings report for TSLA\'s latest quarterly results.',
    },
    {
      id: 'technical',
      pkg: 'longbridge-technical',
      cat: 'research',
      tools: 6,
      name: 'Technical Analysis',
      desc: 'Candlestick patterns, Ichimoku, RSI/MACD/EMA/Bollinger, harmonic patterns, Elliott Wave, Chan Theory (缠论), Smart Money Concepts, and Turtle Trading.',
      prompt: 'Diagnose NVDA on the daily — MACD, RSI, BOLL, and any candlestick patterns.',
    },
    {
      id: 'value-investing',
      pkg: 'longbridge-value-investing',
      cat: 'research',
      tools: 4,
      name: 'Value Investing',
      desc: 'Graham (NCAV/net-net/defensive-investor) and Buffett (economic moat/ROE/FCF) analysis — single-stock diagnostics and batch screening.',
      prompt: 'Run a Buffett moat analysis on AAPL and a Graham net-net screen on HK small caps.',
    },
    {
      id: 'quant',
      pkg: 'longbridge-quant',
      cat: 'research',
      tools: 6,
      name: 'Quant Strategies',
      desc: 'Pairs trading/cointegration, volatility regimes, seasonality, multi-factor models (IC/IR), ML prediction, strategy optimization, and hedging frameworks.',
      prompt: 'Build a pairs trading strategy between NVDA and AMD and backtest it.',
    },
    {
      id: 'portfolio',
      pkg: 'longbridge-portfolio',
      cat: 'portfolio',
      tools: 8,
      tagType: 'hot',
      name: 'Portfolio & Account',
      desc: 'Account assets, equity/fund positions, P&L, cash flow, statements, margin ratios, buy-power, order management, and DCA recurring investments.',
      prompt: 'Review my portfolio performance this month and show which stocks dragged it down.',
    },
  ],

  ui: {
    catLabels: {
      all:        'All',
      meta:       'Platform',
      quote:      'Market',
      research:   'Research',
      derivative: 'Derivatives',
      discovery:  'Discovery',
      portfolio:  'Portfolio',
    },
    title: '13 Skills, covering every move in your trading day',
    subtitle: 'Each Skill is a packaged set of tools, callable by any supported AI client. Click any card to see install instructions and details.',
    searchPlaceholder: 'Search skills',
    noResults: (q) => `No skills matching "${q}". Try a different keyword, or`,
    clear: 'clear search',
    showMore: (n) => `Show ${n} more`,
    collapse: 'Collapse',
    installTitle: 'Install all Skills at once',
    installHint: 'Send this command to any AI assistant and it will guide you through installation.',
    copy: 'Copy',
    copied: 'Copied!',
    modalPromptLabel: 'Example prompt',
    modalInstallLabel: 'Install',
    tagLabels: {
      hot:  'Popular',
      risk: 'High Risk',
    },
  },
}
