import type { CatalogLocale } from '../types'

export const locale: CatalogLocale = {
  skills: [
    {
      id: 'longbridge',
      pkg: 'longbridge',
      cat: 'meta',
      tools: 8,
      tagType: 'hot',
      name: 'Longbridge Overview',
      desc: 'Full-stack financial data and trading platform — CLI, Python/Rust SDK, MCP, and LLM integration.',
      prompt: 'What is NVDA\'s current price, recent news, and how does it affect my positions?',
    },
    {
      id: 'quote',
      pkg: 'longbridge-quote',
      cat: 'quote',
      tools: 3,
      tagType: 'hot',
      name: 'Real-time Quote',
      desc: 'Real-time quotes, static reference, and valuation indices for HK/US/A-share/Singapore stocks — price, change, volume, PE/PB, turnover rate.',
      prompt: 'Get me AAPL, TSLA, and 9988.HK current price and change.',
    },
    {
      id: 'depth',
      pkg: 'longbridge-depth',
      cat: 'quote',
      tools: 3,
      name: 'Order Book Depth',
      desc: 'Level-2 5/10-level bid/ask orderbook, HK broker queue, and tick-by-tick trade data.',
      prompt: 'What does TSLA\'s 5-level bid/ask orderbook look like right now?',
    },
    {
      id: 'kline',
      pkg: 'longbridge-kline',
      cat: 'quote',
      tools: 2,
      name: 'K-line / Intraday',
      desc: 'Candlestick/OHLCV data for 1m/5m/15m/30m/1h/day/week/month/year periods, plus today\'s intraday minute series.',
      prompt: 'Pull NVDA\'s daily chart for the past 6 months and show the trend.',
    },
    {
      id: 'capital-flow',
      pkg: 'longbridge-capital-flow',
      cat: 'quote',
      tools: 2,
      name: 'Capital Flow',
      desc: 'Intraday capital-flow time series and large/medium/small order distribution for a single stock. Same-day data only.',
      prompt: 'How much net institutional inflow did 700.HK see today?',
    },
    {
      id: 'fx',
      pkg: 'longbridge-fx',
      cat: 'quote',
      tools: 1,
      name: 'Exchange Rate',
      desc: 'Real-time FX rates for all Longbridge-supported currencies. Multi-currency portfolio conversion and cross-rate derivation.',
      prompt: 'What\'s USD/HKD today? Convert my whole portfolio to USD.',
    },
    {
      id: 'fundamental',
      pkg: 'longbridge-fundamental',
      cat: 'research',
      tools: 6,
      name: 'Fundamentals',
      desc: 'Company financials — revenue, net income, EPS, ROE, margins, cash flow, dividend history, analyst consensus, and ratings.',
      prompt: 'Give me NVDA\'s latest quarterly revenue, gross margin, and EPS.',
    },
    {
      id: 'valuation',
      pkg: 'longbridge-valuation',
      cat: 'research',
      tools: 4,
      name: 'Valuation',
      desc: 'Current PE/PB/PS/EV-EBITDA snapshot, 1–3 year historical percentile, industry median, and industry rank.',
      prompt: 'Where does Apple\'s current PE sit in its historical percentile?',
    },
    {
      id: 'peer-comparison',
      pkg: 'longbridge-peer-comparison',
      cat: 'research',
      tools: 1,
      name: 'Peer Comparison',
      desc: '2–5 symbol comparison matrix — valuation, price, revenue KPIs, and market cap, with cross-currency caveats.',
      prompt: 'Compare NVDA, AMD, and INTC on valuation and revenue growth.',
    },
    {
      id: 'earnings',
      pkg: 'longbridge-earnings',
      cat: 'research',
      tools: 1,
      tagType: 'hot',
      name: 'Earnings Report',
      desc: 'Institutional-grade post-earnings report (8–12 page DOCX) — beat/miss, segment breakdown, margin trends, guidance, and valuation.',
      prompt: 'Do a post-earnings report for TSLA\'s latest quarterly results.',
    },
    {
      id: 'corporate',
      pkg: 'longbridge-corporate',
      cat: 'research',
      tools: 5,
      name: 'Company Profile',
      desc: 'Major shareholders, executives, corporate actions (splits/dividends/rights), parent–subsidiary relations, and company overview.',
      prompt: 'Who are AAPL\'s major shareholders? Any recent management changes?',
    },
    {
      id: 'flows',
      pkg: 'longbridge-flows',
      cat: 'research',
      tools: 5,
      name: 'Smart Money',
      desc: '13F institutional portfolios, ETF/fund holders, Form 4 insider trades (US), short interest, and HK broker holdings.',
      prompt: 'Who added the most AMD in the latest 13F? How high is short interest?',
    },
    {
      id: 'catalyst-radar',
      pkg: 'longbridge-catalyst-radar',
      cat: 'research',
      tools: 4,
      tagType: 'hot',
      name: 'Catalyst Radar',
      desc: 'Watchlist monitoring radar — scans 7 catalyst dimensions (earnings, funds, insiders, ratings…) and generates morning/evening briefings.',
      prompt: 'Give me my pre-market morning briefing for today.',
    },
    {
      id: 'news',
      pkg: 'longbridge-news',
      cat: 'research',
      tools: 3,
      name: 'News & Filings',
      desc: 'Stock news, regulatory filings, and community discussion — classified by catalyst type with sentiment analysis.',
      prompt: 'Summarize META\'s AI-related news from the past week.',
    },
    {
      id: 'ah-premium',
      pkg: 'longbridge-ah-premium',
      cat: 'research',
      tools: 2,
      name: 'A/H Premium',
      desc: 'A/H premium ratio for Mainland-Chinese dual-listed companies — historical premium time series or today\'s intraday curve.',
      prompt: 'Show me ICBC\'s (1398.HK) A/H premium trend over the past year.',
    },
    {
      id: 'derivatives',
      pkg: 'longbridge-derivatives',
      cat: 'derivative',
      tools: 5,
      tagType: 'hot',
      name: 'Options & Warrants',
      desc: 'US/HK options chain with IV and Greeks, open interest; HK warrants and CBBCs with issuer listings.',
      prompt: 'List TSLA call options expiring next week near the money.',
    },
    {
      id: 'market-temp',
      pkg: 'longbridge-market-temp',
      cat: 'discovery',
      tools: 3,
      name: 'Market Temperature',
      desc: 'Market temperature index (0–100), trading session times, and trading day calendar including half-days.',
      prompt: 'What\'s the US market temperature today? Is it overheating?',
    },
    {
      id: 'calendar',
      pkg: 'longbridge-calendar',
      cat: 'discovery',
      tools: 5,
      name: 'Events Calendar',
      desc: 'Forward-looking calendar — earnings, dividends, IPOs, macro releases (CPI/NFP/FOMC), and market holidays.',
      prompt: 'What are the major earnings and macro data releases next week?',
    },
    {
      id: 'anomaly',
      pkg: 'longbridge-anomaly',
      cat: 'discovery',
      tools: 2,
      name: 'Intraday Anomalies',
      desc: 'Market anomaly scanner and price-by-volume distribution — unusual price/volume movements or a stock\'s intraday volume profile.',
      prompt: 'What anomalies hit HK stocks today? Where is TSLA\'s volume concentrated?',
    },
    {
      id: 'constituent',
      pkg: 'longbridge-constituent',
      cat: 'discovery',
      tools: 1,
      name: 'Index Members',
      desc: 'Constituent stocks of an index or ETF, sortable by change, price, turnover, capital inflow, or market cap.',
      prompt: 'Top 10 S&P 500 gainers today.',
    },
    {
      id: 'security-list',
      pkg: 'longbridge-security-list',
      cat: 'discovery',
      tools: 2,
      name: 'Security Directory',
      desc: 'US overnight-eligible securities directory and HK broker participant dictionary (broker_id ↔ name).',
      prompt: 'List the securities available for US overnight trading.',
    },
    {
      id: 'watchlist',
      pkg: 'longbridge-watchlist',
      cat: 'discovery',
      tools: 2,
      name: 'Watchlist View',
      desc: 'Read-only access to your Longbridge watchlist groups and symbols — pair with real-time quotes for fast scanning.',
      prompt: 'How did my "AI Compute" watchlist group perform today?',
    },
    {
      id: 'watchlist-admin',
      pkg: 'longbridge-watchlist-admin',
      cat: 'discovery',
      tools: 4,
      name: 'Watchlist Manager',
      desc: 'Create/rename/delete groups and add/remove symbols — every mutation requires a two-step preview + confirm.',
      prompt: 'Add AVGO and MRVL to my "AI Compute" watchlist group.',
    },
    {
      id: 'orders',
      pkg: 'longbridge-orders',
      cat: 'trade',
      tools: 5,
      name: 'Orders & History',
      desc: 'Read-only — today\'s/historical orders, executions, cash flow (deposits, withdrawals, dividends, settlements).',
      prompt: 'Show me my executions and dividend records from last month.',
    },
    {
      id: 'alert',
      pkg: 'longbridge-alert',
      cat: 'trade',
      tools: 4,
      name: 'Price Alerts',
      desc: 'Price alerts — list, add, enable/disable, or delete. Every mutation requires a two-step preview + confirm.',
      prompt: 'Alert me when NVDA reaches 200.',
    },
    {
      id: 'dca',
      pkg: 'longbridge-dca',
      cat: 'trade',
      tools: 6,
      tagType: 'risk',
      name: 'DCA Plans',
      desc: 'Recurring-investment (DCA) plans — list, create, update/pause/resume/stop. Every mutation is two-step confirmed.',
      prompt: 'Create a monthly 500 USD DCA plan for AAPL.',
    },
    {
      id: 'subscriptions',
      pkg: 'longbridge-subscriptions',
      cat: 'trade',
      tools: 1,
      name: 'Push Subscriptions',
      desc: 'List active real-time WebSocket subscriptions in the current CLI session — symbols, types, periods. Diagnostic only.',
      prompt: 'What real-time data streams am I currently subscribed to?',
    },
    {
      id: 'positions',
      pkg: 'longbridge-positions',
      cat: 'portfolio',
      tools: 5,
      name: 'Holdings & Assets',
      desc: 'Stock/fund positions, multi-currency cash, margin ratio (initial/maintenance/forced), and max buy/sell quantity.',
      prompt: 'What are all my HK stock positions and total floating P&L?',
    },
    {
      id: 'portfolio',
      pkg: 'longbridge-portfolio',
      cat: 'portfolio',
      tools: 5,
      tagType: 'hot',
      name: 'Account Analysis',
      desc: 'Account-level analysis — total market value, cash share, period P&L, stock contribution ranking, industry/currency exposure.',
      prompt: 'Review my portfolio performance this month — who dragged it down?',
    },
    {
      id: 'statement',
      pkg: 'longbridge-statement',
      cat: 'portfolio',
      tools: 2,
      name: 'Statements',
      desc: 'Daily/monthly account statements — list and export as CSV or markdown for accounting, tax filing, or audit.',
      prompt: 'Export last month\'s statement — holdings and cash flow as CSV.',
    },
  ],

  ui: {
    catLabels: {
      all:        'All',
      quote:      'Market',
      research:   'Research',
      derivative: 'Derivatives',
      discovery:  'Discovery',
      trade:      'Trade',
      portfolio:  'Portfolio',
      meta:       'Platform',
    },
    title: '30 Skills, covering every move in your trading day',
    subtitle: 'Each Skill is a packaged set of tools, callable by any supported AI client. Click any card to see install instructions and details.',
    searchPlaceholder: 'Search skills',
    noResults: (q) => `No skills matching "${q}". Try a different keyword, or`,
    clear: 'clear search',
    showMore: (n) => `Show ${n} more`,
    collapse: 'Collapse',
    installTitle: 'Install all Skills at once',
    installHint: 'Send this command to any AI assistant and it will guide you through installation.',
    copy: 'Copy',
    copied: 'Copied!',
    modalPromptLabel: 'Example prompt',
    modalInstallLabel: 'Install',
    tagLabels: {
      hot:  'Popular',
      risk: 'High Risk',
    },
  },
}
