import type { CatalogLocale } from '../types'

export const locale: CatalogLocale = {
  skills: [
    {
      id: 'longbridge',
      pkg: 'longbridge',
      cat: 'meta',
      tools: 8,
      tagType: 'hot',
      name: '长桥总览',
      desc: 'Longbridge 平台入口，覆盖 CLI / Python / Rust SDK / MCP / LLMs.txt 集成。',
      prompt: '帮我看下 NVDA 现价、新闻和我的持仓影响。',
    },
    {
      id: 'quote',
      pkg: 'longbridge-quote',
      cat: 'quote',
      tools: 3,
      tagType: 'hot',
      name: '实时行情',
      desc: '港 / 美 / A 股 / 新加坡实时报价、静态信息与估值指数（PE/PB/换手率）。',
      prompt: '帮我看 AAPL、TSLA、9988.HK 现价和涨跌幅。',
    },
    {
      id: 'depth',
      pkg: 'longbridge-depth',
      cat: 'quote',
      tools: 3,
      name: '盘口深度',
      desc: 'Level-2 五/十档买卖盘、HK 经纪商队列、逐笔 tick 成交。',
      prompt: 'TSLA 现在的买卖五档分布如何？',
    },
    {
      id: 'kline',
      pkg: 'longbridge-kline',
      cat: 'quote',
      tools: 2,
      name: 'K 线 / 分时',
      desc: '1m / 5m / 15m / 30m / 1h / 日 / 周 / 月 / 年 K 线，历史区间与今日分时。',
      prompt: '调出 NVDA 近半年日 K，看下走势。',
    },
    {
      id: 'capital-flow',
      pkg: 'longbridge-capital-flow',
      cat: 'quote',
      tools: 2,
      name: '资金流向',
      desc: '日内资金流时间序列与大 / 中 / 小单分布（仅当日，无历史区间）。',
      prompt: '今天 700.HK 主力资金净流入多少？',
    },
    {
      id: 'fx',
      pkg: 'longbridge-fx',
      cat: 'quote',
      tools: 1,
      name: '汇率',
      desc: '所有 Longbridge 支持币种的实时汇率，多币种持仓换算与 cross-rate 推导。',
      prompt: '今天美元兑港币多少？把我组合统一换成 USD。',
    },
    {
      id: 'fundamental',
      pkg: 'longbridge-fundamental',
      cat: 'research',
      tools: 6,
      name: '基本面',
      desc: '财报 KPI、同比 / 环比、分红历史、EPS 一致预期、机构评级、公司动作。',
      prompt: 'NVDA 最新季度营收、毛利率和 EPS 给我。',
    },
    {
      id: 'valuation',
      pkg: 'longbridge-valuation',
      cat: 'research',
      tools: 4,
      name: '估值分析',
      desc: 'PE / PB / PS / EV-EBITDA 当前值，1–3 年历史百分位，行业中位与排名。',
      prompt: '苹果当前 PE 在历史百分位的什么位置？',
    },
    {
      id: 'peer-comparison',
      pkg: 'longbridge-peer-comparison',
      cat: 'research',
      tools: 1,
      name: '同业对比',
      desc: '2–5 只标的横向对比矩阵：估值、价格、KPI、市值，自动标注币种风险。',
      prompt: 'NVDA、AMD、INTC 三家估值与营收增速对比。',
    },
    {
      id: 'earnings',
      pkg: 'longbridge-earnings',
      cat: 'research',
      tools: 1,
      tagType: 'hot',
      name: '财报点评',
      desc: '机构级季报点评：8–12 页 DOCX 报告 + 对话纪要，覆盖 Beat/Miss、分部、指引、估值。',
      prompt: '帮我做 TSLA 最新季报的 post-earnings 报告。',
    },
    {
      id: 'corporate',
      pkg: 'longbridge-corporate',
      cat: 'research',
      tools: 5,
      name: '公司画像',
      desc: '股东结构、高管与董事会、公司简介、拆股 / 派息历史、母子公司关系。',
      prompt: 'AAPL 大股东都有谁？高管最近有变动吗？',
    },
    {
      id: 'flows',
      pkg: 'longbridge-flows',
      cat: 'research',
      tools: 5,
      name: '资金面',
      desc: '13F 机构持仓、ETF 基金持有、Form 4 内部人、空头数据、HK 经纪商持仓。',
      prompt: 'AMD 最近 13F 谁加仓最多？空头比例多高？',
    },
    {
      id: 'catalyst-radar',
      pkg: 'longbridge-catalyst-radar',
      cat: 'research',
      tools: 4,
      tagType: 'hot',
      name: '催化雷达',
      desc: '自选股监控雷达，扫描 7 维催化（财报超预期、资金、内部人、评级…），生成晨晚报。',
      prompt: '给我今天的自选盘前晨报。',
    },
    {
      id: 'news',
      pkg: 'longbridge-news',
      cat: 'research',
      tools: 3,
      name: '新闻 / 公告',
      desc: '单股新闻、监管文件、社区讨论按催化 / 监管 / 战略 / 财务等分类，附情绪倾向。',
      prompt: 'META 最近一周和 AI 相关的新闻整理一下。',
    },
    {
      id: 'ah-premium',
      pkg: 'longbridge-ah-premium',
      cat: 'research',
      tools: 2,
      name: 'A/H 溢价',
      desc: '两地上市公司 A/H 股价差与溢价率，历史日 K 或今日分时曲线。',
      prompt: '工行 (1398.HK) 过去一年的 A/H 溢价走势。',
    },
    {
      id: 'derivatives',
      pkg: 'longbridge-derivatives',
      cat: 'derivative',
      tools: 5,
      tagType: 'hot',
      name: '期权与窝轮',
      desc: '美股 / 港股期权链、IV 与 Greeks、持仓量；港股窝轮 / 牛熊证报价与发行人列表。',
      prompt: 'TSLA 下周到期、平值附近的看涨期权列一下。',
    },
    {
      id: 'market-temp',
      pkg: 'longbridge-market-temp',
      cat: 'discovery',
      tools: 3,
      name: '市场温度',
      desc: '0–100 市场情绪温度、交易时段、交易日历（含半日市），判断是否开盘。',
      prompt: '美股今天市场温度多少？是不是过热？',
    },
    {
      id: 'calendar',
      pkg: 'longbridge-calendar',
      cat: 'discovery',
      tools: 5,
      name: '事件日历',
      desc: '前瞻性日历：财报、除权除息、IPO、宏观数据（CPI / 非农 / FOMC）、休市日。',
      prompt: '下周美股有哪些重要财报和宏观数据？',
    },
    {
      id: 'anomaly',
      pkg: 'longbridge-anomaly',
      cat: 'discovery',
      tools: 2,
      name: '盘中异动',
      desc: '市场或单股的盘中异动榜，以及单股价格成交分布（筹码 / volume profile）。',
      prompt: '今天港股有哪些异动？TSLA 筹码集中在哪？',
    },
    {
      id: 'constituent',
      pkg: 'longbridge-constituent',
      cat: 'discovery',
      tools: 1,
      name: '指数成分',
      desc: '指数 / ETF 成分股清单，按涨跌、价格、成交、净流入、市值多维排序。',
      prompt: '标普 500 今天涨幅榜前 10。',
    },
    {
      id: 'security-list',
      pkg: 'longbridge-security-list',
      cat: 'discovery',
      tools: 2,
      name: '标的目录',
      desc: '美股夜盘可交易标的目录、HK 经纪商参与者字典（broker_id ↔ 名称）。',
      prompt: '美股夜盘可交易的标的列出一下。',
    },
    {
      id: 'watchlist',
      pkg: 'longbridge-watchlist',
      cat: 'discovery',
      tools: 2,
      name: '自选浏览',
      desc: '只读访问我的自选分组与组内标的，配合实时报价快速看变动。',
      prompt: '我的「AI 算力」分组今天表现如何？',
    },
    {
      id: 'watchlist-admin',
      pkg: 'longbridge-watchlist-admin',
      cat: 'discovery',
      tools: 4,
      name: '自选管理',
      desc: '建组 / 改名 / 删组、增删自选；写操作走两步预览 + 确认协议。',
      prompt: '把 AVGO、MRVL 加进我的「AI 算力」分组。',
    },
    {
      id: 'orders',
      pkg: 'longbridge-orders',
      cat: 'trade',
      tools: 5,
      name: '订单与流水',
      desc: '只读：今日 / 历史订单、单笔状态、成交明细、出入金 / 分红 / 结算流水。',
      prompt: '我上个月的成交明细和分红记录。',
    },
    {
      id: 'alert',
      pkg: 'longbridge-alert',
      cat: 'trade',
      tools: 4,
      name: '价格提醒',
      desc: '价格提醒的增 / 删 / 启用 / 停用，写操作走预览 + 确认；只读列表无门槛。',
      prompt: 'NVDA 涨到 200 时提醒我。',
    },
    {
      id: 'dca',
      pkg: 'longbridge-dca',
      cat: 'trade',
      tools: 6,
      tagType: 'risk',
      name: '定投计划',
      desc: '创建 / 修改 / 暂停 / 停止定投计划；每次都要复述参数确认。',
      prompt: '帮我建一个每月 500 USD 定投 AAPL 的计划。',
    },
    {
      id: 'subscriptions',
      pkg: 'longbridge-subscriptions',
      cat: 'trade',
      tools: 1,
      name: '推送订阅',
      desc: '查看当前 CLI 会话的实时 WebSocket 订阅（symbols / sub_types / 周期），诊断用。',
      prompt: '我现在订阅了哪些实时数据？',
    },
    {
      id: 'positions',
      pkg: 'longbridge-positions',
      cat: 'portfolio',
      tools: 5,
      name: '持仓 / 资产',
      desc: '股票 + 基金持仓、多币种现金、保证金率（初始 / 维持 / 强平）、最大可买卖数量。',
      prompt: '我现在所有港股持仓和总浮盈是多少？',
    },
    {
      id: 'portfolio',
      pkg: 'longbridge-portfolio',
      cat: 'portfolio',
      tools: 5,
      tagType: 'hot',
      name: '账户分析',
      desc: '账户总市值、现金占比、区间 P&L、单股贡献排行、行业 / 币种暴露、PnL 曲线。',
      prompt: '复盘一下我这个月的组合表现，谁拖了后腿？',
    },
    {
      id: 'statement',
      pkg: 'longbridge-statement',
      cat: 'portfolio',
      tools: 2,
      name: '对账单',
      desc: '日 / 月对账单清单与分项 CSV / Markdown 导出，用于记账、报税、审计。',
      prompt: '把上个月月结单的持仓和现金流导出 CSV。',
    },
  ],

  ui: {
    catLabels: {
      all: '全部',
      quote: '行情数据',
      research: '基本面研究',
      derivative: '衍生品',
      discovery: '行情发现',
      trade: '交易与提醒',
      portfolio: '账户与持仓',
      meta: '平台',
    },
    title: '30 个 Skill，覆盖你交易日的每个动作',
    subtitle: '每个 Skill 是一组打包的工具，可被任意支持的 AI 客户端调用。点开任意卡片查看安装方式与详细说明。',
    searchPlaceholder: '搜索 Skill',
    noResults: (q) => `没有匹配「${q}」的 Skill。试试别的关键词，或`,
    clear: '清除搜索',
    showMore: (n) => `展开剩余 ${n} 个`,
    collapse: '收起',
    installTitle: '一次装好全部 Skill',
    installHint: '把下面这条命令发给任何 AI 助手，它会带你完成安装。',
    copy: '复制',
    copied: '已复制',
    modalPromptLabel: '示例 Prompt',
    modalInstallLabel: '安装',
    tagLabels: {
      hot: '热门',
      risk: '高风险',
    },
  },
}
