import type { CatalogLocale } from '../types'

export const locale: CatalogLocale = {
  skills: [
    {
      id: 'longbridge',
      pkg: 'longbridge',
      cat: 'meta',
      tools: 10,
      tagType: 'hot',
      name: '长桥总览',
      desc: 'Longbridge 平台总入口，覆盖 CLI / Python / Rust SDK / MCP / LLMs.txt 集成，可用于任何行情与账户查询。',
      prompt: '帮我看下 NVDA 现价、新闻和我的持仓影响。',
    },
    {
      id: 'market-data',
      pkg: 'longbridge-market-data',
      cat: 'quote',
      tools: 8,
      tagType: 'hot',
      name: '行情数据',
      desc: '实时报价、K 线、盘口、资金流、市场温度、汇率、IPO 日历、ADR 溢价，覆盖港 / 美 / A 股 / 新加坡。',
      prompt: 'NVDA 现价、近半年日 K 和今日资金流给我看看。',
    },
    {
      id: 'content',
      pkg: 'longbridge-content',
      cat: 'discovery',
      tools: 4,
      name: '新闻与公告',
      desc: '单股新闻、SEC 监管文件（10-K/10-Q/8-K）、社区话题讨论和市场规则查询。',
      prompt: 'META 最近一周和 AI 相关的新闻整理一下。',
    },
    {
      id: 'intel',
      pkg: 'longbridge-intel',
      cat: 'discovery',
      tools: 8,
      tagType: 'hot',
      name: '市场情报',
      desc: '策略筛选、热度排行、异动侦测、ETF 资金流、板块轮动、产业链、晨报生成和 ARK 式颠覆创新分析。',
      prompt: '帮我筛选美股科技股，MACD 金叉 + 市值 500 亿以上。',
    },
    {
      id: 'watchlist',
      pkg: 'longbridge-watchlist',
      cat: 'discovery',
      tools: 5,
      name: '自选与提醒',
      desc: '自选股分组管理、价格提醒与社区股票清单，所有写操作需二次确认。',
      prompt: '把 NVDA、TSLA 加进「AI 算力」自选，NVDA 涨到 200 提醒我。',
    },
    {
      id: 'derivatives',
      pkg: 'longbridge-derivatives',
      cat: 'derivative',
      tools: 5,
      tagType: 'hot',
      name: '期权与窝轮',
      desc: '美股 / 港股期权链，含 IV、Greeks、持仓量；港股窝轮 / 牛熊证报价与发行人列表。',
      prompt: 'TSLA 下周到期、平值附近的看涨期权，给我 IV 和 delta。',
    },
    {
      id: 'research',
      pkg: 'longbridge-research',
      cat: 'research',
      tools: 6,
      name: '机构研究',
      desc: '机构评级、目标价一致预期、EPS 预测、股东结构、基金持仓、内部人交易（Form 4）、空头数据和行业排名。',
      prompt: 'NVDA 最大机构持有人是谁？上季度怎么操作的？',
    },
    {
      id: 'fundamentals',
      pkg: 'longbridge-fundamentals',
      cat: 'research',
      tools: 8,
      name: '基本面',
      desc: '财务三表、估值倍数（PE/PB/PS）、业务分部、分红、经营数据、公司动作、高管画像与 DCF 框架。',
      prompt: 'NVDA 最新季度营收、毛利率、EPS 和 PE 历史百分位给我。',
    },
    {
      id: 'earnings',
      pkg: 'longbridge-earnings',
      cat: 'research',
      tools: 3,
      tagType: 'hot',
      name: '财报分析',
      desc: '财报前瞻（上季度指引复盘、事件追踪、Q&A 要点、关注框架）与财报点评（超预期分析、分部、指引、估值）。',
      prompt: '帮我做 TSLA 最新季报的 post-earnings 分析。',
    },
    {
      id: 'technical',
      pkg: 'longbridge-technical',
      cat: 'research',
      tools: 6,
      name: '技术分析',
      desc: 'K 线形态、一目均衡表、RSI/MACD/EMA/布林带、谐波形态、艾略特波浪、缠论、Smart Money 与海龟交易信号。',
      prompt: '帮我诊断 NVDA 日线：MACD、RSI、布林带，有没有 K 线形态信号？',
    },
    {
      id: 'value-investing',
      pkg: 'longbridge-value-investing',
      cat: 'research',
      tools: 4,
      name: '价值投资',
      desc: '格雷厄姆（NCAV / 净流动资产 / 防御型投资者）与巴菲特（护城河 / ROE / FCF）分析，支持单股诊断与批量筛选。',
      prompt: '帮我对 AAPL 做巴菲特护城河分析，再筛一批港股格雷厄姆净净值股票。',
    },
    {
      id: 'quant',
      pkg: 'longbridge-quant',
      cat: 'research',
      tools: 6,
      name: '量化策略',
      desc: '配对交易 / 协整、波动率策略、季节性、多因子模型（IC/IR）、机器学习预测、策略优化与对冲框架。',
      prompt: '帮我做 NVDA 和 AMD 的配对交易策略，并回测一下。',
    },
    {
      id: 'portfolio',
      pkg: 'longbridge-portfolio',
      cat: 'portfolio',
      tools: 8,
      tagType: 'hot',
      name: '账户与持仓',
      desc: '账户资产、股票 / 基金持仓、盈亏、资金流水、对账单、保证金率、买入力估算、订单管理与定投计划。',
      prompt: '复盘一下我这个月的组合表现，谁拖了后腿？',
    },
  ],

  ui: {
    catLabels: {
      all:        '全部',
      meta:       '平台',
      quote:      '行情数据',
      research:   '基本面研究',
      derivative: '衍生品',
      discovery:  '行情发现',
      portfolio:  '账户与持仓',
    },
    title: '13 个 Skill，覆盖你交易日的每个动作',
    subtitle: '每个 Skill 是一组打包的工具，可被任意支持的 AI 客户端调用。点开任意卡片查看安装方式与详细说明。',
    searchPlaceholder: '搜索 Skill',
    noResults: (q) => `没有匹配「${q}」的 Skill。试试别的关键词，或`,
    clear: '清除搜索',
    showMore: (n) => `展开剩余 ${n} 个`,
    collapse: '收起',
    installTitle: '一次装好全部 Skill',
    installHint: '把下面这条命令发给任何 AI 助手，它会带你完成安装。',
    copy: '复制',
    copied: '已复制',
    modalPromptLabel: '示例 Prompt',
    modalInstallLabel: '安装',
    tagLabels: {
      hot:  '热门',
      risk: '高风险',
    },
  },
}
