import type { CatalogLocale } from '../types'

export const locale: CatalogLocale = {
  skills: [
    {
      id: 'longbridge',
      pkg: 'longbridge',
      cat: 'meta',
      tools: 10,
      tagType: 'hot',
      name: '長橋總覽',
      desc: 'Longbridge 平台總入口，覆蓋 CLI / Python / Rust SDK / MCP / LLMs.txt 整合，可用於任何行情與賬戶查詢。',
      prompt: '幫我看下 NVDA 現價、新聞和我的持倉影響。',
    },
    {
      id: 'market-data',
      pkg: 'longbridge-market-data',
      cat: 'quote',
      tools: 8,
      tagType: 'hot',
      name: '行情數據',
      desc: '即時報價、K 線、盤口、資金流、市場溫度、匯率、IPO 日曆、ADR 溢價，覆蓋港 / 美 / A 股 / 新加坡。',
      prompt: 'NVDA 現價、近半年日 K 和今日資金流給我看看。',
    },
    {
      id: 'content',
      pkg: 'longbridge-content',
      cat: 'discovery',
      tools: 4,
      name: '新聞與公告',
      desc: '單股新聞、SEC 監管文件（10-K/10-Q/8-K）、社區話題討論和市場規則查詢。',
      prompt: 'META 最近一週和 AI 相關的新聞整理一下。',
    },
    {
      id: 'intel',
      pkg: 'longbridge-intel',
      cat: 'discovery',
      tools: 8,
      tagType: 'hot',
      name: '市場情報',
      desc: '策略篩選、熱度排行、異動偵測、ETF 資金流、板塊輪動、產業鏈、晨報生成和 ARK 式顛覆創新分析。',
      prompt: '幫我篩選美股科技股，MACD 金叉 + 市值 500 億以上。',
    },
    {
      id: 'watchlist',
      pkg: 'longbridge-watchlist',
      cat: 'discovery',
      tools: 5,
      name: '自選與提醒',
      desc: '自選股分組管理、價格提醒與社區股票清單，所有寫操作需二次確認。',
      prompt: '把 NVDA、TSLA 加進「AI 算力」自選，NVDA 漲到 200 提醒我。',
    },
    {
      id: 'derivatives',
      pkg: 'longbridge-derivatives',
      cat: 'derivative',
      tools: 5,
      tagType: 'hot',
      name: '期權與窩輪',
      desc: '美股 / 港股期權鏈，含 IV、Greeks、持倉量；港股窩輪 / 牛熊證報價與發行人列表。',
      prompt: 'TSLA 下週到期、平值附近的看漲期權，給我 IV 和 delta。',
    },
    {
      id: 'research',
      pkg: 'longbridge-research',
      cat: 'research',
      tools: 6,
      name: '機構研究',
      desc: '機構評級、目標價一致預期、EPS 預測、股東結構、基金持倉、內部人交易（Form 4）、空頭數據和行業排名。',
      prompt: 'NVDA 最大機構持有人是誰？上季度怎麼操作的？',
    },
    {
      id: 'fundamentals',
      pkg: 'longbridge-fundamentals',
      cat: 'research',
      tools: 8,
      name: '基本面',
      desc: '財務三表、估值倍數（PE/PB/PS）、業務分部、分紅、經營數據、公司動作、高管畫像與 DCF 框架。',
      prompt: 'NVDA 最新季度營收、毛利率、EPS 和 PE 歷史百分位給我。',
    },
    {
      id: 'earnings',
      pkg: 'longbridge-earnings',
      cat: 'research',
      tools: 3,
      tagType: 'hot',
      name: '財報分析',
      desc: '財報前瞻（上季度指引複盤、事件追蹤、Q&A 要點、關注框架）與財報點評（超預期分析、分部、指引、估值）。',
      prompt: '幫我做 TSLA 最新季報的 post-earnings 分析。',
    },
    {
      id: 'technical',
      pkg: 'longbridge-technical',
      cat: 'research',
      tools: 6,
      name: '技術分析',
      desc: 'K 線形態、一目均衡表、RSI/MACD/EMA/布林帶、諧波形態、艾略特波浪、纏論、Smart Money 與海龜交易信號。',
      prompt: '幫我診斷 NVDA 日線：MACD、RSI、布林帶，有沒有 K 線形態信號？',
    },
    {
      id: 'value-investing',
      pkg: 'longbridge-value-investing',
      cat: 'research',
      tools: 4,
      name: '價值投資',
      desc: '格雷厄姆（NCAV / 淨流動資產 / 防禦型投資者）與巴菲特（護城河 / ROE / FCF）分析，支持單股診斷與批量篩選。',
      prompt: '幫我對 AAPL 做巴菲特護城河分析，再篩一批港股格雷厄姆淨淨值股票。',
    },
    {
      id: 'quant',
      pkg: 'longbridge-quant',
      cat: 'research',
      tools: 6,
      name: '量化策略',
      desc: '配對交易 / 協整、波動率策略、季節性、多因子模型（IC/IR）、機器學習預測、策略優化與對沖框架。',
      prompt: '幫我做 NVDA 和 AMD 的配對交易策略，並回測一下。',
    },
    {
      id: 'portfolio',
      pkg: 'longbridge-portfolio',
      cat: 'portfolio',
      tools: 8,
      tagType: 'hot',
      name: '賬戶與持倉',
      desc: '賬戶資產、股票 / 基金持倉、盈虧、資金流水、對賬單、保證金率、買入力估算、訂單管理與定投計劃。',
      prompt: '複盤一下我這個月的組合表現，誰拖了後腿？',
    },
  ],

  ui: {
    catLabels: {
      all:        '全部',
      meta:       '平台',
      quote:      '行情數據',
      research:   '基本面研究',
      derivative: '衍生品',
      discovery:  '行情發現',
      portfolio:  '賬戶與持倉',
    },
    title: '13 個 Skill，覆蓋你交易日的每個動作',
    subtitle: '每個 Skill 是一組打包的工具，可被任意支持的 AI 客戶端調用。點開任意卡片查看安裝方式與詳細說明。',
    searchPlaceholder: '搜索 Skill',
    noResults: (q) => `沒有匹配「${q}」的 Skill。試試別的關鍵詞，或`,
    clear: '清除搜索',
    showMore: (n) => `展開剩餘 ${n} 個`,
    collapse: '收起',
    installTitle: '一次裝好全部 Skill',
    installHint: '把下面這條命令發給任何 AI 助手，它會帶你完成安裝。',
    copy: '複製',
    copied: '已複製',
    modalPromptLabel: '示例 Prompt',
    modalInstallLabel: '安裝',
    tagLabels: {
      hot:  '熱門',
      risk: '高風險',
    },
  },
}
