import type { CatalogLocale } from '../types'

export const locale: CatalogLocale = {
  skills: [
    {
      id: 'longbridge',
      pkg: 'longbridge',
      cat: 'meta',
      tools: 8,
      tagType: 'hot',
      name: '長橋總覽',
      desc: 'Longbridge 平台入口，覆蓋 CLI / Python / Rust SDK / MCP / LLMs.txt 整合。',
      prompt: '幫我看下 NVDA 現價、新聞和我的持倉影響。',
    },
    {
      id: 'quote',
      pkg: 'longbridge-quote',
      cat: 'quote',
      tools: 3,
      tagType: 'hot',
      name: '即時行情',
      desc: '港 / 美 / A 股 / 新加坡即時報價、靜態資訊與估值指數（PE/PB/換手率）。',
      prompt: '幫我看 AAPL、TSLA、9988.HK 現價和漲跌幅。',
    },
    {
      id: 'depth',
      pkg: 'longbridge-depth',
      cat: 'quote',
      tools: 3,
      name: '盤口深度',
      desc: 'Level-2 五/十檔買賣盤、HK 經紀商隊列、逐筆 tick 成交。',
      prompt: 'TSLA 現在的買賣五檔分佈如何？',
    },
    {
      id: 'kline',
      pkg: 'longbridge-kline',
      cat: 'quote',
      tools: 2,
      name: 'K 線 / 分時',
      desc: '1m / 5m / 15m / 30m / 1h / 日 / 週 / 月 / 年 K 線，歷史區間與今日分時。',
      prompt: '調出 NVDA 近半年日 K，看下走勢。',
    },
    {
      id: 'capital-flow',
      pkg: 'longbridge-capital-flow',
      cat: 'quote',
      tools: 2,
      name: '資金流向',
      desc: '日內資金流時間序列與大 / 中 / 小單分佈（僅當日，無歷史區間）。',
      prompt: '今天 700.HK 主力資金淨流入多少？',
    },
    {
      id: 'fx',
      pkg: 'longbridge-fx',
      cat: 'quote',
      tools: 1,
      name: '匯率',
      desc: '所有 Longbridge 支持幣種的即時匯率，多幣種持倉換算與 cross-rate 推導。',
      prompt: '今天美元兌港幣多少？把我組合統一換成 USD。',
    },
    {
      id: 'fundamental',
      pkg: 'longbridge-fundamental',
      cat: 'research',
      tools: 6,
      name: '基本面',
      desc: '財報 KPI、同比 / 環比、分紅歷史、EPS 一致預期、機構評級、公司動作。',
      prompt: 'NVDA 最新季度營收、毛利率和 EPS 給我。',
    },
    {
      id: 'valuation',
      pkg: 'longbridge-valuation',
      cat: 'research',
      tools: 4,
      name: '估值分析',
      desc: 'PE / PB / PS / EV-EBITDA 當前值，1–3 年歷史百分位，行業中位與排名。',
      prompt: '蘋果當前 PE 在歷史百分位的什麼位置？',
    },
    {
      id: 'peer-comparison',
      pkg: 'longbridge-peer-comparison',
      cat: 'research',
      tools: 1,
      name: '同業對比',
      desc: '2–5 只標的橫向對比矩陣：估值、價格、KPI、市值，自動標註幣種風險。',
      prompt: 'NVDA、AMD、INTC 三家估值與營收增速對比。',
    },
    {
      id: 'earnings',
      pkg: 'longbridge-earnings',
      cat: 'research',
      tools: 1,
      tagType: 'hot',
      name: '財報點評',
      desc: '機構級季報點評：8–12 頁 DOCX 報告 + 對話紀要，覆蓋 Beat/Miss、分部、指引、估值。',
      prompt: '幫我做 TSLA 最新季報的 post-earnings 報告。',
    },
    {
      id: 'corporate',
      pkg: 'longbridge-corporate',
      cat: 'research',
      tools: 5,
      name: '公司畫像',
      desc: '股東結構、高管與董事會、公司簡介、拆股 / 派息歷史、母子公司關係。',
      prompt: 'AAPL 大股東都有誰？高管最近有變動嗎？',
    },
    {
      id: 'flows',
      pkg: 'longbridge-flows',
      cat: 'research',
      tools: 5,
      name: '資金面',
      desc: '13F 機構持倉、ETF 基金持有、Form 4 內部人、空頭數據、HK 經紀商持倉。',
      prompt: 'AMD 最近 13F 誰加倉最多？空頭比例多高？',
    },
    {
      id: 'catalyst-radar',
      pkg: 'longbridge-catalyst-radar',
      cat: 'research',
      tools: 4,
      tagType: 'hot',
      name: '催化雷達',
      desc: '自選股監控雷達，掃描 7 維催化（財報超預期、資金、內部人、評級…），生成晨晚報。',
      prompt: '給我今天的自選盤前晨報。',
    },
    {
      id: 'news',
      pkg: 'longbridge-news',
      cat: 'research',
      tools: 3,
      name: '新聞 / 公告',
      desc: '單股新聞、監管文件、社區討論按催化 / 監管 / 戰略 / 財務等分類，附情緒傾向。',
      prompt: 'META 最近一週和 AI 相關的新聞整理一下。',
    },
    {
      id: 'ah-premium',
      pkg: 'longbridge-ah-premium',
      cat: 'research',
      tools: 2,
      name: 'A/H 溢價',
      desc: '兩地上市公司 A/H 股價差與溢價率，歷史日 K 或今日分時曲線。',
      prompt: '工行 (1398.HK) 過去一年的 A/H 溢價走勢。',
    },
    {
      id: 'derivatives',
      pkg: 'longbridge-derivatives',
      cat: 'derivative',
      tools: 5,
      tagType: 'hot',
      name: '期權與窩輪',
      desc: '美股 / 港股期權鏈、IV 與 Greeks、持倉量；港股窩輪 / 牛熊證報價與發行人列表。',
      prompt: 'TSLA 下週到期、平值附近的看漲期權列一下。',
    },
    {
      id: 'market-temp',
      pkg: 'longbridge-market-temp',
      cat: 'discovery',
      tools: 3,
      name: '市場溫度',
      desc: '0–100 市場情緒溫度、交易時段、交易日曆（含半日市），判斷是否開盤。',
      prompt: '美股今天市場溫度多少？是不是過熱？',
    },
    {
      id: 'calendar',
      pkg: 'longbridge-calendar',
      cat: 'discovery',
      tools: 5,
      name: '事件日曆',
      desc: '前瞻性日曆：財報、除權除息、IPO、宏觀數據（CPI / 非農 / FOMC）、休市日。',
      prompt: '下週美股有哪些重要財報和宏觀數據？',
    },
    {
      id: 'anomaly',
      pkg: 'longbridge-anomaly',
      cat: 'discovery',
      tools: 2,
      name: '盤中異動',
      desc: '市場或單股的盤中異動榜，以及單股價格成交分佈（籌碼 / volume profile）。',
      prompt: '今天港股有哪些異動？TSLA 籌碼集中在哪？',
    },
    {
      id: 'constituent',
      pkg: 'longbridge-constituent',
      cat: 'discovery',
      tools: 1,
      name: '指數成分',
      desc: '指數 / ETF 成分股清單，按漲跌、價格、成交、淨流入、市值多維排序。',
      prompt: '標普 500 今天漲幅榜前 10。',
    },
    {
      id: 'security-list',
      pkg: 'longbridge-security-list',
      cat: 'discovery',
      tools: 2,
      name: '標的目錄',
      desc: '美股夜盤可交易標的目錄、HK 經紀商參與者字典（broker_id ↔ 名稱）。',
      prompt: '美股夜盤可交易的標的列出一下。',
    },
    {
      id: 'watchlist',
      pkg: 'longbridge-watchlist',
      cat: 'discovery',
      tools: 2,
      name: '自選瀏覽',
      desc: '唯讀訪問我的自選分組與組內標的，配合即時報價快速看變動。',
      prompt: '我的「AI 算力」分組今天表現如何？',
    },
    {
      id: 'watchlist-admin',
      pkg: 'longbridge-watchlist-admin',
      cat: 'discovery',
      tools: 4,
      name: '自選管理',
      desc: '建組 / 改名 / 刪組、增刪自選；寫操作走兩步預覽 + 確認協議。',
      prompt: '把 AVGO、MRVL 加進我的「AI 算力」分組。',
    },
    {
      id: 'orders',
      pkg: 'longbridge-orders',
      cat: 'trade',
      tools: 5,
      name: '訂單與流水',
      desc: '唯讀：今日 / 歷史訂單、單筆狀態、成交明細、出入金 / 分紅 / 結算流水。',
      prompt: '我上個月的成交明細和分紅記錄。',
    },
    {
      id: 'alert',
      pkg: 'longbridge-alert',
      cat: 'trade',
      tools: 4,
      name: '價格提醒',
      desc: '價格提醒的增 / 刪 / 啟用 / 停用，寫操作走預覽 + 確認；唯讀列表無門檻。',
      prompt: 'NVDA 漲到 200 時提醒我。',
    },
    {
      id: 'dca',
      pkg: 'longbridge-dca',
      cat: 'trade',
      tools: 6,
      tagType: 'risk',
      name: '定投計劃',
      desc: '創建 / 修改 / 暫停 / 停止定投計劃；每次都要複述參數確認。',
      prompt: '幫我建一個每月 500 USD 定投 AAPL 的計劃。',
    },
    {
      id: 'subscriptions',
      pkg: 'longbridge-subscriptions',
      cat: 'trade',
      tools: 1,
      name: '推送訂閱',
      desc: '查看當前 CLI 會話的即時 WebSocket 訂閱（symbols / sub_types / 週期），診斷用。',
      prompt: '我現在訂閱了哪些即時數據？',
    },
    {
      id: 'positions',
      pkg: 'longbridge-positions',
      cat: 'portfolio',
      tools: 5,
      name: '持倉 / 資產',
      desc: '股票 + 基金持倉、多幣種現金、保證金率（初始 / 維持 / 強平）、最大可買卖數量。',
      prompt: '我現在所有港股持倉和總浮盈是多少？',
    },
    {
      id: 'portfolio',
      pkg: 'longbridge-portfolio',
      cat: 'portfolio',
      tools: 5,
      tagType: 'hot',
      name: '賬戶分析',
      desc: '賬戶總市值、現金佔比、區間 P&L、單股貢獻排行、行業 / 幣種暴露、PnL 曲線。',
      prompt: '複盤一下我這個月的組合表現，誰拖了後腿？',
    },
    {
      id: 'statement',
      pkg: 'longbridge-statement',
      cat: 'portfolio',
      tools: 2,
      name: '對賬單',
      desc: '日 / 月對賬單清單與分項 CSV / Markdown 匯出，用於記賬、報稅、審計。',
      prompt: '把上個月月結單的持倉和現金流匯出 CSV。',
    },
  ],

  ui: {
    catLabels: {
      all: '全部',
      quote: '行情數據',
      research: '基本面研究',
      derivative: '衍生品',
      discovery: '行情發現',
      trade: '交易與提醒',
      portfolio: '賬戶與持倉',
      meta: '平台',
    },
    title: '30 個 Skill，覆蓋你交易日的每個動作',
    subtitle: '每個 Skill 是一組打包的工具，可被任意支持的 AI 客戶端調用。點開任意卡片查看安裝方式與詳細說明。',
    searchPlaceholder: '搜索 Skill',
    noResults: (q) => `沒有匹配「${q}」的 Skill。試試別的關鍵詞，或`,
    clear: '清除搜索',
    showMore: (n) => `展開剩餘 ${n} 個`,
    collapse: '收起',
    installTitle: '一次裝好全部 Skill',
    installHint: '把下面這條命令發給任何 AI 助手，它會帶你完成安裝。',
    copy: '複製',
    copied: '已複製',
    modalPromptLabel: '示例 Prompt',
    modalInstallLabel: '安裝',
    tagLabels: {
      hot: '熱門',
      risk: '高風險',
    },
  },
}
